ALTER TABLE domain_common.event_journal
  ADD COLUMN IF NOT EXISTS event_id TEXT,
  ADD COLUMN IF NOT EXISTS schema_name TEXT,
  ADD COLUMN IF NOT EXISTS schema_version INT,
  ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ DEFAULT now(),
  ADD COLUMN IF NOT EXISTS effective_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS actor TEXT,
  ADD COLUMN IF NOT EXISTS origin TEXT,
  ADD COLUMN IF NOT EXISTS correlation_id TEXT,
  ADD COLUMN IF NOT EXISTS causation_id TEXT,
  ADD COLUMN IF NOT EXISTS checksum TEXT;
